'use strict';

const assert = require('assert');
const { statusPageHtml } = require('../src/status-page');

const html = statusPageHtml();
const inlineScript = /<script>([\s\S]*)<\/script>/.exec(html);
assert.ok(inlineScript, 'status page should include its client script');
new Function(inlineScript[1]);
assert.ok(html.includes('Unavailable saved selection:'));
assert.ok(html.includes('selected disabled'));
assert.ok(html.includes('backend.job_types.includes(jobType)'));
assert.ok(html.includes("backend.ready === true"));
assert.ok(html.includes('Refresh detection'));
assert.ok(html.includes('Save paths &amp; routing'));
assert.ok(html.includes('id="relayCliPaths"'));
assert.ok(html.includes('id="relayTokenDefaults"'));
assert.ok(html.includes('data-relay-token-default'));
assert.ok(html.includes("{ jobType: 'chat'"));
assert.ok(html.includes("{ jobType: 'media.analyze'"));
assert.ok(html.includes('min="512" max="128000"'));
assert.ok(html.includes('Antigravity CLI executable'));
assert.ok(html.includes('data-relay-cli-path'));
assert.ok(html.includes('Saving executable paths'));
assert.ok(html.includes('saveRelaySettings({ quiet: true })'));
assert.ok(html.includes('function followProviderRefresh(refreshState)'));
assert.ok(html.includes('payload.refresh_started === true'));
assert.ok(html.includes('Provider media and audio tests'));
assert.ok(html.includes('aria-label="Provider test types"'));
assert.ok(html.includes('id="provider-test-tab-images"'));
assert.ok(html.includes('id="provider-test-tab-videos"'));
assert.ok(html.includes('id="provider-test-tab-analysis"'));
assert.ok(html.includes('id="provider-test-tab-audio"'));
assert.ok(html.includes('data-provider-test-tab'));
assert.ok(!html.includes('id="provider-test-tab-media"'));
assert.ok(!html.includes('data-provider-media-tab'));
assert.ok(html.includes('id="providerImageTests"'));
assert.ok(html.includes('id="providerVideoTests"'));
assert.ok(html.includes('id="providerAnalysisTests"'));
assert.ok(html.includes('id="providerAudioTests"'));
assert.ok(html.includes('function initProviderTestTabs()'));
assert.ok(!html.includes('function initProviderMediaTabs()'));
assert.ok(html.includes("const imageTests = readyMediaModels(models, backends, 'images', 'image')"));
assert.ok(html.includes('Ultrarealistic scene Cool Kungfu Cat'));
assert.ok(html.includes("const videoModels = readyMediaModels(models, backends, 'videos', 'video')"));
assert.ok(html.includes('function providerTestControls(model, jobType)'));
assert.ok(html.includes('model.test_options'));
assert.ok(html.includes('data-test-option'));
assert.ok(html.includes('generation guidance'));
assert.ok(html.includes('sent directly'));
assert.ok(html.includes('Video analysis'));
assert.ok(html.includes('Local Music Analysis Settings'));
assert.ok(html.includes("const musicAnalysisSettingsUrl = '/v1/music-analysis/settings'"));
assert.ok(html.includes('Selecting xAI Speech-to-Text uploads the chosen audio to xAI'));
assert.ok(html.includes("const relayTestUrl = '/v1/relay/test'"));
assert.ok(html.includes('test_request_id: requestId'));
assert.ok(html.includes('function updateProviderTestProgress()'));
assert.ok(html.includes('data-test-progress'));
assert.ok(html.includes('data-test-progress-bar'));
assert.ok(html.includes('function setProviderTestActivity(card, active, state)'));
assert.ok(html.includes('function settleProviderTestCard(card, job)'));
assert.ok(html.includes('Continuing to follow it here.'));
assert.ok(html.includes("document.querySelector('[data-provider-media-test][data-test-request-id]')"));
assert.ok(html.includes('data-test-result'));
assert.ok(html.includes('function renderProviderTestResult(card, job)'));
assert.ok(html.includes('\\/(?:v1)\\/status\\/jobs\\/\\d+\\/artifacts\\/\\d+'));
assert.ok(!html.includes('\\/(?:v1)\\/status\\/jobs\\/d+\\/artifacts\\/d+'));
assert.ok(html.includes('data-media-preview'));
assert.ok(html.includes('function openMediaLightbox(url, mimeType)'));
assert.ok(html.includes('id="mediaLightboxVideo"'));
assert.ok(html.includes('const video = /^video\\//i.test'));
assert.ok(html.includes('data-provider-test'));
assert.ok(html.includes("const isAudio = jobType === 'transcribe' || jobType === 'music.analyze'"));
assert.ok(html.includes('Reference image (optional)'));
assert.ok(html.includes('data-test-media'));
assert.ok(html.includes('data-test-audio'));
assert.ok(html.includes('Choose a small video file before running this test.'));
assert.ok(html.includes('Choose an audio file before running this test.'));
assert.ok(html.includes('<video src="'));
assert.ok(html.includes('muted preload="metadata" playsinline'));
assert.ok(html.includes('Grok CLI request'));
assert.ok(html.includes('Grok CLI stdout / stderr'));
assert.ok(html.includes('Local CUDA Upscale Settings'));
assert.ok(html.includes("const upscaleSettingsUrl = '/v1/upscale/settings'"));
assert.ok(html.includes("const upscaleSetupUrl = '/v1/upscale/setup'"));
assert.ok(html.includes('id="upscaleInstallActions"'));
assert.ok(html.includes('data-upscale-install'));
assert.ok(html.includes('data-upscale-restricted'));
assert.ok(html.includes('APISR academic-only and GPL-3.0 restriction'));
assert.ok(html.includes('Use Settings → Local CUDA Upscale to install an available pinned model'));
assert.ok(html.includes('Native ×2 and ×4 outputs are never downsampled'));
assert.ok(html.includes('Jobs never download a model, downsample native output, or fall back to CPU'));
assert.ok(html.includes('id="upscaleSetupLog"'));
assert.ok(html.includes('<div class="label">Local Image Generation</div>'));
assert.ok(html.includes("const imageSettingsUrl = '/v1/image/settings'"));
assert.ok(html.includes('payload.capabilities?.resolution_choices'), 'Saving image settings must preserve resolution choices from the capabilities response');
assert.ok(html.includes("const imageSetupUrl = '/v1/image/setup'"));
assert.ok(html.includes('id="imageInstallActions"'));
assert.ok(html.includes('data-image-install'));
assert.ok(html.includes('Repair / Reinstall Model'));
assert.ok(html.includes('id="imageDefaultResolution"'));
assert.ok(html.includes('resolution_choices'));
assert.ok(html.includes('Default resolution'));
assert.ok(html.includes('id="imageSetupLog"'));
assert.ok(html.includes('data-settings-section="image"'));
assert.ok(html.includes('Use Settings → Local Image to set up the Diffusers runtime'));
assert.ok(html.includes('text-to-image only'), 'Model cards must clearly identify text-to-image-only models');
assert.ok(html.includes('referenceLimit === 0 ?'), 'The provider test must hide reference-image input for text-to-image-only models');
assert.ok(html.includes('function setupFailureText(payload, fallback)'));
assert.ok(html.includes("const asrSetupUrl = '/v1/asr/setup'"));
assert.ok(html.includes('data-install-asr-model'));
assert.ok(html.includes('Install model'));
assert.ok(html.includes('id="asrSetupLog"'));
assert.ok(html.includes('function setupAsrModel(button)'));
assert.ok(html.includes("payload.details && payload.details.log"));
assert.ok(html.includes('That download is explicit'));
assert.ok(html.includes('id="settings-nav"'));
assert.ok(html.includes('data-settings-section="providers"'));
assert.ok(html.includes('data-settings-section="runtime"'));
assert.ok(html.includes('data-settings-section="tests"'));
assert.ok(html.includes('id="relayRuntimeSettings"'));
assert.ok(html.includes('id="relayProviderOptions"'));
assert.ok(html.includes('id="saveRelayRuntimeSettings"'));
assert.ok(html.includes('function collectRelaySettingsPayload(section)'));
assert.ok(html.includes("saveRelaySettings({ section: 'runtime' })"));
assert.ok(html.includes('function restoreRelaySection(section, preserved)'));
assert.ok(html.includes("captureFormSnapshots(['relay', 'runtime'])"));
assert.ok(html.includes("captureFormSnapshots([section])"));
assert.ok(html.includes('id="asrTranscribeTimeout"'));
assert.ok(html.includes('id="asrCudaPaths"'));
assert.ok(html.includes('id="asrQwenTorchIndexUrl"'));
assert.ok(html.includes('id="musicAnalysisTimeout"'));
assert.ok(html.includes('id="upscaleApisrVenvPath"'));
assert.ok(html.includes('id="upscaleTimeout"'));
assert.ok(html.includes('id="upscaleTile"'));
assert.ok(html.includes('id="upscalePrecision"'));
assert.ok(html.includes('function parseHash()'));
assert.ok(html.includes('function selectSettingsSection(section'));
assert.ok(html.includes('function renderLiveJobList(jobs)'));
assert.ok(html.includes('function renderLiveDetail(job)'));
assert.ok(html.includes('id="liveJobList"'));
assert.ok(html.includes('id="liveDetailBody"'));
assert.ok(html.includes('id="debugHealthList"'));
assert.ok(html.includes('id="debugFailureList"'));
assert.ok(html.includes('id="rawStatusFilter"'));
assert.ok(html.includes('function renderDebugHealth(payload, ok)'));
assert.ok(html.includes('function captureFormSnapshots(keys)'));
assert.ok(html.includes('class="app-shell"'));
assert.ok(html.includes('id="healthGrid"'));
assert.ok(html.includes('data-live-filter'));
assert.ok(html.includes('data-live-filter="completed"'));
assert.ok(html.includes('data-live-filter-count="all"'));
assert.ok(html.includes('id="liveJobSearch"'));
assert.ok(html.includes('function pendingLiveJob(requestId)'));
assert.ok(html.includes('function liveJobMatchesSearch(job)'));
assert.ok(html.includes('Waiting for this job to appear in live updates.'));
assert.ok(html.includes("liveFilter === 'completed'"));
assert.ok(html.includes('class="live-status-pill'));
assert.ok(html.includes('id="liveDetailStatus"'));
assert.ok(html.includes('class="live-artifact-download"'));
assert.ok(html.includes('currentStatus.jobs = jobs'));
assert.ok(html.includes('let livePinned = false'));
assert.ok(html.includes("setHash('live')"));
assert.ok(html.includes('jobs.active'));
assert.ok(html.includes('!seenLiveRequestIds.has(selectedLiveRequestId)'));
assert.ok(html.includes('min-height: 240px'));
assert.ok(html.includes('data-open-live-job'));
assert.ok(html.includes('--accent:'));

console.log('status page tests passed');

assert.ok(html.includes('data-settings-section="pairing"'));
assert.ok(html.includes('id="persistentPairingCodeInput"'));
assert.ok(html.includes('type="password"'));
assert.ok(html.includes("const pairingCodeSettingsUrl = '/v1/relay/pairing-code'"));
assert.ok(html.includes('The code is never returned to this page after saving.'));
