'use strict';

const assert = require('assert');
const { statusPageHtml } = require('../src/status-page');

const html = statusPageHtml();
const inlineScript = /<script>([\s\S]*)<\/script>/.exec(html);
assert.ok(inlineScript, 'status page should include its client script');
new Function(inlineScript[1]);
assert.ok(html.includes('Unavailable saved selection:'));
assert.ok(html.includes('selected disabled'));
assert.ok(html.includes('backend.job_types.includes(jobType)'));
assert.ok(html.includes("backend.ready === true"));
assert.ok(html.includes('Refresh detection'));
assert.ok(html.includes('Save paths &amp; routing'));
assert.ok(html.includes('id="relayCliPaths"'));
assert.ok(html.includes('Antigravity CLI executable'));
assert.ok(html.includes('data-relay-cli-path'));
assert.ok(html.includes('Saving executable paths'));
assert.ok(html.includes('saveRelaySettings({ quiet: true })'));
assert.ok(html.includes('function followProviderRefresh(refreshState)'));
assert.ok(html.includes('payload.refresh_started === true'));
assert.ok(html.includes('Provider media and audio tests'));
assert.ok(html.includes('aria-label="Provider test types"'));
assert.ok(html.includes('id="provider-test-tab-media"'));
assert.ok(html.includes('id="provider-test-tab-audio"'));
assert.ok(html.includes('data-provider-test-tab'));
assert.ok(html.includes('id="provider-media-tab-images"'));
assert.ok(html.includes('id="provider-media-tab-videos"'));
assert.ok(html.includes('id="provider-media-tab-analysis"'));
assert.ok(html.includes('id="providerImageTests"'));
assert.ok(html.includes('id="providerVideoTests"'));
assert.ok(html.includes('id="providerAnalysisTests"'));
assert.ok(html.includes('id="providerAudioTests"'));
assert.ok(html.includes('function initProviderTestTabs()'));
assert.ok(html.includes('function initProviderMediaTabs()'));
assert.ok(html.includes("const imageTests = readyMediaModels(models, backends, 'images', 'image')"));
assert.ok(html.includes("const videoModels = readyMediaModels(models, backends, 'videos', 'video')"));
assert.ok(html.includes('data-test-size'));
assert.ok(html.includes('data-test-quality'));
assert.ok(html.includes('data-test-seconds'));
assert.ok(html.includes('data-test-model'));
assert.ok(html.includes('Resolution and clip length are sent directly to the OpenAI Videos API.'));
assert.ok(html.includes('Video analysis'));
assert.ok(html.includes('Local Music Analysis Settings'));
assert.ok(html.includes("const musicAnalysisSettingsUrl = '/v1/music-analysis/settings'"));
assert.ok(html.includes('Selecting xAI Speech-to-Text uploads the chosen audio to xAI'));
assert.ok(html.includes("const relayTestUrl = '/v1/relay/test'"));
assert.ok(html.includes('await Promise.all([refresh().catch(() => {}), loadRelaySettings().catch(() => {})])'));
assert.ok(html.includes('data-provider-test'));
assert.ok(html.includes("const isAudio = jobType === 'transcribe' || jobType === 'music.analyze'"));
assert.ok(html.includes('Reference image (optional)'));
assert.ok(html.includes('data-test-media'));
assert.ok(html.includes('data-test-audio'));
assert.ok(html.includes('Choose a small video file before running this test.'));
assert.ok(html.includes('Choose an audio file before running this test.'));
assert.ok(html.includes('<video src="'));
assert.ok(html.includes('controls preload="metadata" playsinline'));
assert.ok(html.includes('Grok CLI request'));
assert.ok(html.includes('Grok CLI stdout / stderr'));

console.log('status page tests passed');
